### ISSUE TITLE
throw an error when trying to write without tags

### ISSUE THREAD

**Issue by VladVega** [opentsdb-js/datum#2]
Writing a `datum` without any tags doesn't work so `toString` could throw an error when there are no tags? Just a thought. I could put up a PR if you find this idea be a good one.

http://opentsdb.net/docs/build/html/user_guide/writing.html

**Comment by kgryte** [comment]
@VladVega Must have missed that previously. A PR would be welcome. Thanks!

**Comment by VladVega** [comment]
Sounds good. Will do.
